workflows:
  build-apk-and-web:
    name: Build APK and Web
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build Web
        script: |
          flutter build web --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/web/**
